create database sklep_db;
drop database sklep_db;DROP SCHEMA public CASCADE;

ALTER TABLE pupil
  ALTER COLUMN id_pupil ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE SEQUENCE pupil_id_seq;

alter table pupil alter column id_pupil set default nextval('pupil_id_seq');

ALTER SEQUENCE pupil_id_seq
  OWNED BY pupil.id_pupil;

select pupil_id_seq;

-- drop sequence pupil_id_seq cascade ;
-- drop sequence pupil_id_pupil_seq1 cascade
-- drop table pupil cascade
-- drop table

select * from pupil;

INSERT INTO PATRON VALUES(0, 'email1@gmail.com', 'Dora', 'Cruz', (select now()));
INSERT INTO PATRON VALUES(1, 'email2@gmail.com', 'Melvin', 'Beck', (select now()));

INSERT INTO PUPIL VALUES(null, 'email2@gmail.com', 'Esther', 'Cruz', 0, 3);
INSERT INTO PUPIL VALUES('email2@gmail.com', 'Don', 'Cruz', 0);

-- INSERT INTO PATRON VALUES(1, 'greezlie@gmail.com', 'Konrad', 'Bosak', (select now()));
-- INSERT INTO PATRON VALUES(0, 'greezlie@gmail.com', 'Konrad', 'Bosak', (select now()));
-- drop table patron CASCADE

insert into limitation values (0, 'Przemoc');
insert into limitation values (1, 'Seks');
insert into limitation values (2, 'Dyskryminacja');
insert into limitation values (3, 'Narkotyki');
insert into limitation values (4, 'Strach');
insert into limitation values (5, 'Wulgarny język');
insert into limitation values (6, 'Hazard');
insert into limitation values (7, 'Gra online');

select * from limitation;

--id, limit, patron, pupil
insert into limit_restriction values (0, 0, 0, 0); -- przemoc dla Esthera Cruza od Dory Cruz
insert into limit_restriction values (1, 4, 0, 0); -- Strach dla Esthera Cruza od Dory Cruz
insert into limit_restriction values (2, 2, 0, 1); -- Dyskryminacja dla Don Cruza od Dory Cruz

select * from limit_restriction;

SELECT * FROM PATRON;

select * from limitation lmt
  right join limit_restriction lr
on lmt.id_limit = lr.limitation_id_limit
where lr.pupil_id_pupil = 0;

INSERT INTO PEGI_RESTRICTION VALUES(1, 0, 2, 0);
INSERT INTO PEGI_RESTRICTION VALUES(2, 0, 3, 1);

SELECT * FROM PEGI_RESTRICTION;

-- DROP TABLE pegi CASCADE;

INSERT INTO PEGI VALUES (0, 'PEGI 3');
INSERT INTO PEGI VALUES (1, 'PEGI 7');
INSERT INTO PEGI VALUES (2, 'PEGI 12');
INSERT INTO PEGI VALUES (3, 'PEGI 16');
INSERT INTO PEGI VALUES (4, 'PEGI 18');

select * from pegi;

insert into manager values (0, (select now()), 'manager@gmail.com', 'Konrad', 'Bosak');
insert into manager values (1, (select now()), 'manager2@gmail.com', 'Karol', 'Bosak');

select * from manager;

insert into soft_category values (0, 'RPG');
insert into soft_category values (1, 'Symulacje');
insert into soft_category values (2, 'Sportowe');
insert into soft_category values (3, 'Akcji');
insert into soft_category values (4, 'Strategiczne');
insert into soft_category values (5, 'Zręcznościowe');
insert into soft_category values (6, 'Wojenne');

select * from soft_category;

insert into software values (0,
                             'komputerowa gra survivalowa rozwijana przez studio People Can Fly oraz Epic Games, wydana w formie wczesnego dostępu 25 lipca 2017. Gra zawiera tryb współpracy i battle royale.',
                             'Fortnite',
                             0,
                             2);

insert into software values (1,
                             'komputerowa gra survivalowa o otwartym świecie stworzona przez Markusa Perssona i rozwijana przez studio Mojang AB[a]. Minecraft pozwala graczom na budowanie i niszczenie obiektów położonych w losowo generowanym świecie gry.',
                             'Minecraft',
                             0,
                             1);

insert into software values (2,
                             'gra platformowa stworzona przez Team Meat. Jest bezpośrednim następcą, stworzonej w technologii Flash gry Meat Boy. ',
                             'Super Meat Boy',
                             0,
                             2);

insert into software values (3,
                             'Weź udział w największym konflikcie w historii w Battlefield™ V – seria wraca do swoich korzeni dzięki zupełnie nowemu spojrzeniu na II wojnę światową.',
                             'Battlefield V',
                             0,
                             (select p.id_pegi from pegi p where p.value = 'PEGI 18'));

insert into software values (4,
                             'Wszędzie tam, gdzie trup ściele się gęsto, wkracza on, THE CLEANER! Człowiek od brudnej roboty, specjalista w sprzątaniu miejsc zbrodni, pozbywaniu się ciał, wyrzucaniu dowodów i usuwaniu śladów krwi.',
                             'Serial Cleaner',
                             0,
                             (select p.id_pegi from pegi p where p.value = 'PEGI 16'));


insert into software values (5,
                             'Dzień Powrotu, rok 2102. Dwadzieścia pięć lat po wybuchu bomb razem z innymi mieszkańcami krypty – wybranymi spośród najwspanialszych i najbardziej inteligentnych obywateli kraju – wychodzisz na powierzchnię wprost w objęcia postnuklearnej Ameryki.',
                             'Fallout 76',
                             1,
                             (select p.id_pegi from pegi p where p.value = 'PEGI 18'));



insert into software values (6,
                             'gra komputerowa z gatunku first-person shooter osadzona w realiach II wojny światowej, stworzona przez szwedzkie studio Digital Illusions CE',
                             'Battlefield 1942',
                             1,
                             (select p.id_pegi from pegi p where p.value = 'PEGI 16'));


insert into software values (6,
                             '',
                             '',
                             1,
                             (select p.id_pegi from pegi p where p.value = 'PEGI 18'));

select * from software;


insert into category_assign values (0, 3, 0);
insert into category_assign values (1, 0, 1);
insert into category_assign values (2, 5, 1);
insert into category_assign values (3, 5, 2);
insert into category_assign values (4, 3, 3);
insert into category_assign values (5, 6, 3);
insert into category_assign values (6, 3, 4);
insert into category_assign values (7, 3, 5);
insert into category_assign values (8, 0, 5);
insert into category_assign values (9, 6, 6);
insert into category_assign values (10, 3, 6);

select * from category_assign;
